name: pos-tagger
channels:
  - defaults
dependencies:
  - appnope=0.1.4=py313hca03da5_0
  - asttokens=3.0.0=py313hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - comm=0.2.1=py313hca03da5_0
  - debugpy=1.8.16=py313h0962b89_0
  - decorator=5.2.1=py313hca03da5_0
  - executing=2.2.1=py313hca03da5_0
  - expat=2.7.1=h313beb8_0
  - ipykernel=6.30.1=py313hca03da5_0
  - ipython=9.5.0=py313hca03da5_0
  - ipython_pygments_lexers=1.1.1=py313hca03da5_0
  - jedi=0.19.2=py313hca03da5_0
  - jupyter_client=8.6.3=py313hca03da5_0
  - jupyter_core=5.8.1=py313hca03da5_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libsodium=1.0.20=h897f8a9_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.1.7=py313hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py313hca03da5_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py313hca03da5_1
  - parso=0.8.4=py313hca03da5_0
  - pexpect=4.9.0=py313hca03da5_0
  - pip=25.2=pyhc872135_0
  - platformdirs=4.3.7=py313hca03da5_0
  - prompt-toolkit=3.0.52=py313hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py313h254cc4a_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py313hca03da5_0
  - python=3.13.5=h2eb94d5_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python_abi=3.13=1_cp313
  - pyzmq=27.1.0=py313h854a7ef_0
  - readline=8.3=h0b18652_0
  - setuptools=78.1.1=py313hca03da5_0
  - six=1.17.0=py313hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=py313hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py313h80987f9_0
  - traitlets=5.14.3=py313hca03da5_0
  - wcwidth=0.2.13=py313hca03da5_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - conllu==6.0.0
      - flatbuffers==25.9.23
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.75.1
      - h5py==3.14.0
      - idna==3.10
      - joblib==1.5.2
      - keras==3.11.3
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - namex==0.1.0
      - numpy==2.3.3
      - opt-einsum==3.4.0
      - optree==0.17.0
      - pandas==2.3.3
      - pillow==11.3.0
      - protobuf==6.32.1
      - pygments==2.19.2
      - pytz==2025.2
      - requests==2.32.5
      - rich==14.1.0
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
